# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.exercise_service:
        class: AppBundle\Service\ExerciseService
        autowire: true
    app.serializer_data_service:
        class: AppBundle\Service\SerializerDataService
        autowire: true
